# Project: dohoa
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = robot.o
LINKOBJ  = robot.o
LIBS     = -L"D:/Anh/Do_hoa_MT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libopengl32.a Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libfreeglut.a Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libglu32.a
INCS     = -I"D:/Anh/Do_hoa_MT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"D:/Anh/Do_hoa_MT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = dohoa.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

robot.o: robot.cpp
	$(CPP) -c robot.cpp -o robot.o $(CXXFLAGS)
